### ISSUE TITLE
"SyntaxError: Unexpected token ..." when running lacona init

### ISSUE THREAD

**Issue by BenMusch** [brandonhorst/lacona-cli#1]
Here's the error:

```
/usr/local/lib/node_modules/lacona-cli/index.js:27
function getDefaultDotIgnore (...additional) {
                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

I'm assuming there's some dependency I'm missing, since I've never used node before, so I have almost nothing installed other than the dependencies declared in the lacona-cli package

**Comment by brandonhorst** [comment]
Currently, `lacona-cli` requires you to be running Node 6 (as the ... syntax is not supported in <=5.x). I think I'm going to remove that dependency for the next release though, by pretranspiling with Babel. But for now, just upgrade to Node v6 and you should be good to go.
